name: Libris-CI

on: [push]

jobs:
  debug:
    name: Build Debug x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Display MSBuild version
        run: msbuild -version

      - name: Restore all the packages
        run: nuget restore Libris.sln

      - name: Build Debug x64
        run: msbuild /p:Configuration=Debug


  release:
    name: Build Release x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Display MSBuild version
        run: msbuild -version

      - name: Restore all the packages
        run: nuget restore Libris.sln

      - name: Build Release x64
        run: msbuild /p:Configuration=Release


  tests:
    name: Test the full project
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore all the packages
        run: nuget restore Libris.sln

      - name: Run full tests
        run: dotnet test
